title: Hello! I'm Marin Petrov
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Marin Petrov - rigger, founder, software developer.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marinpetrov.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Marin Petrov # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a Character Technical Director, Software Developer, Hacker, Painter, Family man. I was fortunate to have worked at one of the best animation studios in the world on features like "Ice Age", "Rio", "Ferdinand" and many more. I also co-founded a remote self-managed VR Game Studio and a remote self-managed software company called RGBNotes, which was later acquired by Amazon. # add description
social-twitter: troll_lock # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: scroll # add your Github handle
social-linkedin: marinpetrov # add your Linkedin handle
social-email: petrov.marin@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
